Algoritmo "ENTRADA E SAÍDA DE DADOS"
// Descrição   : ENTRADA E SAÍDA DE DADOS
// Autor(a)    : Gabriel
// Data atual  : 02/08/2020
Var
// Seção de Declarações das variáveis 
nome: caractere
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o Nome: ")
leia(nome)
escreval("Digite a idade : ")
leia(idade)

escreval("O nome é: ", nome)
escreval("A idade é: ", idade)

Fimalgoritmo